### PR TITLE
Use log dir setting from checkpoint when restoring

### LINKED ISSUE #32960: SVT:  Regression - Liberty InstantOn app can't start with .spec.serviceability with operator 1.5.0 or later
**Update**:  This issue needs changes from Liberty and Semeru team.  Leo wants to leave the operator [defect 798](https://github.com/WASdev/websphere-liberty-operator/issues/798) open, and he also wants to see work items from Liberty and JVM teams to track this.  I reopen  this issue on Liberty.

========================================================================
This is a regression since this scenario worked ok in Liberty 25.0.0.8 on AKS with Operator 1.4.4

Use _WebSphere Application Server 25.0.0.10 (wlp-1.0.106.cl251020250920-1102) Java 17_

Deploy WebSphereLibertyApplication InstantOn app image on `Azure Kubernetes Service (AKS)` with storage class _azurefile-premium_

AKS cluster nodes
```
% oc get nodes -o wide
NAME                              STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
aks-default-12122487-vmss000000   Ready    <none>   17h   v1.33.2   10.224.0.4    <none>        Ubuntu 22.04.5 LTS   5.15.0-1092-azure   containerd://1.7.28-1
```
I have the following in the app deployment yaml
```
spec:
  serviceability:
    size: 1G
    storageClassName: azurefile-premium
```

The app pod can't start and there is no error on why it failed to start

```
% oc -n ebuy-wlk-ubi9-j17 get po
NAME                  READY   STATUS             RESTARTS      AGE
ebuy-wlk-ubi9-j17-0   0/1     CrashLoopBackOff   2 (20s ago)   56s

% oc -n ebuy-wlk-ubi9-j17 logs ebuy-wlk-ubi9-j17-0  --previous
Found mounted TLS certificates, generating keystore
Found mounted TLS CA certificate, adding to truststore

% oc -n ebuy-wlk-ubi9-j17 get pvc 
NAME                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        VOLUMEATTRIBUTESCLASS   AGE
ebuy-wlk-ubi9-j17-serviceability   Bound    pvc-0c53a767-6f3d-4725-be69-7a397fe4e89f   1G         RWX            azurefile-premium   <unset>                 53s
```

Redeploy the app with the following settings then I can see the server start without resume from the InstantOn checkpoint 
```
spec:
  env:
  - name: CRIU_RESTORE_DISABLE_RECOVERY
    value: "false"
```

### PR DESCRIPTION
**Pull request by tjwatson**
The LOG_DIR env is not allowed to change from checkpoint to restore. This change makes sure we always use the same LOG_DIR from checkpoint to restore.

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

### CODE REVIEW

**Comment by tjwatson** [comment]
!build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=327f40a4-25b2-4702-870a-c85134372f06) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by tjwatson** [comment]
!build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=ebea93c1-890b-48ec-97f8-cbe500af1bd4) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by tjwatson** [comment]
!build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=351db8e8-8a50-4940-bd2c-f9aa73177760) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by tjwatson** [comment]
For diagnostics of the problem see https://github.com/WASdev/websphere-liberty-operator/issues/798#issuecomment-3366628585

File: dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointPhaseTest.java [hunk 1]
```diff
@@ -77,6 +80,43 @@ public void testAfterAppStartMultRestore() throws Exception {
...
+        new File(server.getServerRoot() + "/logsLink2").mkdirs();
+        Files.createSymbolicLink(logs.toPath(), Paths.get("logsLink2"));
+        FATSuite.configureEnvVariable(server, Collections.singletonMap("LOG_DIR", server.getServerRoot() + "/logsLink2"));
+
+        // Not validating on restore because the LibertyServer is not equipt to handle this scenario with log dir changing
+        // Instead of trying to enhance LibertyServer for a very limited scenario we validate the expected console log location here.
+        server.checkpointRestore(false);
+        // Note that we use the original logLink1 location for the console log because InstantOn (criu) does not currently
+        // allow us to swap out the file the process is piping to.
+        server.waitForStringInLog("Launching checkpointFATServer", 100, server.getFileFromLibertyServerRoot("logsLink1/" + getTestMethodNameOnly(testName)));
```
Comment (dazavala) [inline dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointPhaseTest.java:119]: FYI, the test does not also verify server output to dir `logsLink2`. Maybe no concern as the new assertion would verify a file system behavior, not necessarily a server behavior.

File: dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointPhaseTest.java [hunk 2]
```diff
@@ -77,6 +80,43 @@ public void testAfterAppStartMultRestore() throws Exception {
...
+        HttpUtils.findStringInUrl(server, "app2/request", "Got ServletA");
+        server.setStarted();
```
Comment (dazavala) [inline dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointPhaseTest.java]: Curious why `setStarted()` is necessary.

**Review by dazavala — DISMISSED** [review]
Looks good, @tjwatson.  Could use a little dust-up on the copyrights.  Left a couple comments regarding your new test.  Approving now as no changes are mandatory.

File: dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointPhaseTest.java (hunk 1 above)
Comment (tjwatson) [reply dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointPhaseTest.java:119]: I added an assert for messages.log in the logslink2.

File: dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointPhaseTest.java (hunk 2 above)
Comment (tjwatson) [reply dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/CheckpointPhaseTest.java]: I added some comments around the reason here.

**Comment by tjwatson** [comment]
!build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=8780a722-0b64-4455-bfa0-fc57cbb8df45) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by tjwatson** [comment]
> Could use a little dust-up on the copyrights

I updated the copyrights

**Review by dazavala — APPROVED** [review]
Looks good!

**Comment by tjwatson** [comment]
!build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=825c0dc7-a317-46d0-bf9a-0fc49d11df8b) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._
