### PR TITLE
Prevent security manager in LibertyClient and LibertyServer

### LINKED ISSUE #30453: LibertyServer fails to start when passing -Djava.security.manager=allow in Java 24+
When attempting to start the Liberty Server in Java 24+ by passing in the JVM argument `-Djava.security.manager=allow`, the server fails to start because the JVM fails to start.

The messages in the logs looks like:
```
Server failed to start.   Command used to start server was: /home/ci/Build/workspace/ebcTestRunner/dev/autoFVT/image/output/wlp/bin/server
componenttest.exception.TopologyException: Start Server error: The server did not show kernel had started. The server did not show kernel had started. The standard error was: .
 Standard out was: 
Error occurred during initialization of VM
java.lang.Error: A command line option has attempted to allow or enable the Security Manager. Enabling a Security Manager is not supported.
	at java.lang.System.initPhase3(java.base@24-ea/System.java:1947)

.
 Return code was: 22.
 Message was not found in /home/ci/Build/workspace/ebcTestRunner/dev/autoFVT/image/output/wlp/usr/servers/com.ibm.ws.security.java2sec.fat.earAppJ2SecEnblRestricPerm/logs/console.log
	at componenttest.topology.impl.LibertyServer.validateServerStarted(LibertyServer.java:2918)
	at componenttest.topology.impl.LibertyServer.startServerWithArgs(LibertyServer.java:1974)
	at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:1515)
	at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:1497)
	at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:1484)
	at componenttest.topology.impl.LibertyServer.startServer(LibertyServer.java:1235)
        ...
```

### PR DESCRIPTION
**Pull request by gjwatts**
- [X] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [X] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).

Fixes #30453 

In Java 24, the [security manager has been permanently disabled](https://openjdk.org/jeps/486) and throws an error if you attempt to start it by passing the JVM argument `-Djava.security.manager=allow`.  In Java 18, the Liberty Client was updated to add the `-Djava.security.manager=allow` agrument to the JVM if the security manager was needed.  Now in Java 24, the `-Djava.security.manager=allow` argument cannot be passed in or the JVM fails to start.

### CODE REVIEW

**Comment by gjwatts** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=4eea976b-bcd5-40e8-b656-5110ef636675) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Review by mswatosh — DISMISSED** [review]

**Comment by gjwatts** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=76f4b935-102a-4a52-9673-d370642a85c7) - :x: completed with errors/failures.)

_Note: Target locations of links might be accessible only to IBM employees._

**Comment by gjwatts** [comment]
CI-O pipeline failed with one intermittent defect, but did not report back to this PR at the time I checked.  Now running Java 24 testing.

**Comment by gjwatts** [comment]
Decided to change the LibertyServer code with this PR as well.

**Comment by gjwatts** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=43b12ca1-f9e0-4448-b035-6f540db0ff5b) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

File: dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java [hunk 1]
```diff
@@ -1711,10 +1717,14 @@ public ProgramOutput startServerWithArgs(boolean preClean, boolean cleanStart,
 
             startedWithJavaSecurity = bootstrapHasJava2SecProps;
             if (bootstrapHasJava2SecProps) {
-                if (info.majorVersion() >= 18) {
-                    // If we are running on Java 18+, then we need to explicitly enable the security manager
+                if (javaInfo.majorVersion() >= 18 && javaInfo.majorVersion() <= 23) {
```
Comment (jhanders34) [inline dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java]: Not sure why you switched to `javaInfo` instead of using `info`.  `info` is for the server's Java version instead of the test side Java version.

Comment (gjwatts) [reply dev/fattest.simplicity/src/componenttest/topology/impl/LibertyServer.java]: That was a copy/paste error from LibertyClient.  Thanks for catching it!

**Review by jhanders34 — DISMISSED** [review]

**Comment by gjwatts** [comment]
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=8f228e04-2eba-417e-94f1-235daa3b6e54) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

**Review by jhanders34 — APPROVED** [review]

**Comment by gjwatts** [comment]
Starting with this fix in Java 24, the LibertyServer throws a more helpful exception:

```
com.ibm.ws.security.java2sec.fat.EarAppJ2SecEnblNoRestrictPermTest:java.lang.RuntimeException: The security manager is permanently disabled in Java versions 24 and later.  When running FATs, use @MaximumJavaLevel(javaLevel = 23) or disable Java 2 security to prevent this server from failing to start when running in Java 24 or later.
	at componenttest.topology.impl.LibertyServer.startServerWithArgs(LibertyServer.java:1721)
	at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:1515)
	at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:1497)
	at componenttest.topology.impl.LibertyServer.startServerAndValidate(LibertyServer.java:1484)
	at componenttest.topology.impl.LibertyServer.startServer(LibertyServer.java:1235)
	at com.ibm.ws.security.java2sec.fat.CommonTestHelper.startServer(CommonTestHelper.java:245)
	at com.ibm.ws.security.java2sec.fat.CommonTestHelper.startServer(CommonTestHelper.java:204)
	at com.ibm.ws.security.java2sec.fat.CommonTest.commonSetUp(CommonTest.java:174)
	at com.ibm.ws.security.java2sec.fat.CommonTest.commonSetUp(CommonTest.java:113)
	at com.ibm.ws.security.java2sec.fat.EarAppJ2SecEnblNoRestrictPermTest.setUp(EarAppJ2SecEnblNoRestrictPermTest.java:50)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:381)
	at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:185)
```

**Comment by gjwatts** [comment]
Java 24 testing was good.  Merging.
