### PR TITLE
Used JavaInfo isSystemClassAval call, instead of JavaInfo.vendor

### LINKED ISSUE #20562: Test Failure : build.featureStart.aToL_fat: testFeaturesStart
RTC 289893

```
Found the following failure in Semeru 8 run:

junit.framework.AssertionFailedError: 2022-03-22-19:56:07:275 Features(s) [logstashCollector-1.0] did not start/stop cleanly on their own due to the following exceptions: [logstashCollector-1.0=java.lang.Exception: Errors/warnings were found in server features.start.a.to.l.server logs:
<br>[3/22/22 19:52:31:624 PDT] 0000001c com.ibm.ws.health.center.classloader.HCClassLoader           W TRAS4352W: Health Center agent was not found, so JVM monitoring and diagnostic information will not be available.]
at com.ibm.ws.simple.FeaturesStartTestAToL.testFeaturesStart(FeaturesStartTestAToL.java:169)
at componenttest.custom.junit.runner.FATRunner$1.evaluate(FATRunner.java:199)
at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:320)
at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:173)
```

Probably similar to #20561, need to identify the JDK is Semeru and skip the test.

### PR DESCRIPTION
**Pull request by pgunapal**
fixes #20562

- Replaced the call to skip tests for Non-IBM JDKs, to use JavaInfo.isSystemClassAvailable() instead of JavaInfo.forServer(server).vendor().equals(JavaInfo.Vendor.IBM) due to the vendor string change for Semeru Java 8 JDKs to skip LogstashCollector testing.

### CODE REVIEW

**Comment by pgunapal** [comment]
#build

File: dev/build.featureStart.aToL_fat/fat/src/com/ibm/ws/simple/FeaturesStartTestAToL.java [hunk 1]
```diff
@@ -265,8 +265,9 @@ private boolean skipFeature(String feature) throws Exception {
             return true;
 
         if (feature.equalsIgnoreCase("logstashCollector-1.0")) {
-            if (javaInfo.vendor() != JavaInfo.Vendor.IBM) {
-                Log.info(c, testName.getMethodName(), "Skipping feature " + feature + " because it is for IBM JDK only.");
+            if (!(JavaInfo.isSystemClassAvailable("com.ibm.java.diagnostics.healthcenter.agent.mbean.HealthCenter"))) {
+                Log.info(c, testName.getMethodName(),
+                         "Skipping feature " + feature + " because it is for IBM JDK only, and the runtime JDK does not include Health Center.");
                 return true;
             } else if (JAVA_LEVEL >= 11) {
```
Comment (fmhwong) [inline dev/build.featureStart.aToL_fat/fat/src/com/ibm/ws/simple/FeaturesStartTestAToL.java]: Can we remove the Java 11 check now?

Comment (pgunapal) [reply dev/build.featureStart.aToL_fat/fat/src/com/ibm/ws/simple/FeaturesStartTestAToL.java]: Removed the Java 11 check.

**Comment by pgunapal** [comment]
#build

**Review by fmhwong — APPROVED** [review]
LGTM

**Review by fmhwong — APPROVED** [review]
LGTM

**Comment by pgunapal** [comment]
#libby
