### PR TITLE
EJBxCDI ee8 Tests & RepeatTest Servlet Injection Fix

### LINKED ISSUE #2119: Repeat Test does not work with servlet injection or append test name

### PR DESCRIPTION
**Pull request by olendvcook**
#2119
#2014

### CODE REVIEW

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
@aguibert 

What do you think of the changes to FeatureReplacementAction.java and FATRunner.java?

File: dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java [hunk 1]
```diff
@@ -97,6 +97,15 @@ public static void requireFATRunner(String className) {
                                             "class level.");
     }
 
+    @Override
+    protected String testName(FrameworkMethod method) {
+        String testName = method.getName();
+        if (RepeatTestFilter.CURRENT_REPEAT_ACTION != null && !RepeatTestFilter.CURRENT_REPEAT_ACTION.equals("NO_MODIFICATION_ACTION")) {
```
Comment (aguibert) [inline dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java]: could re-order the comparison to avoid the null check:
`if(!"NO_MODIFICATION_ACTION".equals(RepeatTestFilter.CURRENT_REPEAT_ACTION))`

File: dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java [hunk 2]
```diff
@@ -97,6 +97,15 @@ public static void requireFATRunner(String className) {
                                             "class level.");
     }
 
+    @Override
+    protected String testName(FrameworkMethod method) {
+        String testName = method.getName();
```
Comment (aguibert) [inline dev/fattest.simplicity/src/componenttest/custom/junit/runner/FATRunner.java]: instead of fully overriding the default impl of `testName()`, lets instead do `String testName = super.testName()` and then append the repeat action to that.  In case other parts of code hook into the super impl in some way.

File: dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java [hunk 3]
```diff
@@ -314,6 +316,20 @@ public void setup() throws Exception {
             else
                 ClientConfigurationFactory.toFile(configFile, clientConfig);
         }
+
+        // Make sure config update is pushed to the wlp version of the server & client
+        if (serverConfigs.size() > 0) {
```
Comment (aguibert) [inline dev/fattest.simplicity/src/componenttest/rules/repeater/FeatureReplacementAction.java]: Need to also handle the `ALL_SERVERS` case.  Otherwise line 323 will attempt `LibertyServerFactory.getLibertyServer("ALL_SERVERS");` which will fail

**Comment by olendvcook** [comment]
#build - in flight build doesn't have code review changes and will fail some tests

**Comment by tevans78** [comment]
@olendvcook @aguibert The IDs are great to have but in some circumstances they show up as "null". Not a major problem but should probably be fixed. I ran with three tests in a suite, one of which had a RepeatTests on it. The tests which had no repeat had "_null" appended to their name...
```
FATSuite | noConversionTest_null | Success |   | 0.370
FATSuite | converterPrioritySPITest_null | Success |   | 0.048
FATSuite | forcedTypeConverterTest_null | Success |   | 0.355
FATSuite | listConverterTest_null | Success |   | 0.025
FATSuite | setConverterTest_null | Success |   | 0.027
FATSuite | optionalConverterTest_null | Success |   | 0.024
FATSuite | defaultOptionalConverterTest_null | Success |   | 0.025
FATSuite | converterPrioritySPITest_null | Success |   | 0.043
FATSuite | stringConstructorTest_EE7_FEATURES | Success |   | 0.330
FATSuite | stringConstructorMissingTest_EE7_FEATURES | Success |   | 0.044
FATSuite | overrideConverterTest_EE7_FEATURES | Success |   | 0.030
FATSuite | stringConstructorTest_EE8_FEATURES | Success |   | 0.325
FATSuite | stringConstructorMissingTest_EE8_FEATURES | Success |   | 0.038
FATSuite | overrideConverterTest_EE8_FEATURES | Success
```

**Comment by tevans78** [comment]
And sadly, looking closer at the server output, EE7 was never actually used at all :-(

**Comment by olendvcook** [comment]
@tevans78 what suite did you run? so I can check the ee7 problem locally

**Comment by olendvcook** [comment]
@tevans78 I took a look at your configFATVersionCombos branch, copied RepeatConfig11CDI12 which extends EE7FeatureReplacementAction, and I was able to get it to work: 
A CWWKF0012I: The server installed the following features: [servlet-3.1, componenttest-1.0, timedexit-1.0, osgiConsole-1.0, cdi-1.2, mpConfig-1.1].

I think it's because on the Test level you need to pass the servers, on the FatSuite level you do not:
@ClassRule
public static RepeatTests r = RepeatTests.withoutModification().andWith(RepeatConfig11CDI12.INSTANCE.forServers("ConverterServer"));

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
#build

**Comment by olendvcook** [comment]
Note: Was able to match all test failures in latest build to existing defects, but I am waiting to deliver because Buildcon
